baseURL = "https://ishanjawade.github.io/"
languageCode = "en-us"
title = "Ishan"
theme = "classic2000s"
relativeURLs = false

[params]
tagline = "Personal site · Projects · Writing"
github = "https://github.com/ishan"
linkedin = "https://www.linkedin.com/in/ishan"

[menu]
	[[menu.main]]
	name = "Home"
	url = "/"
	weight = 1

	[[menu.main]]
	name = "Portfolio"
	url = "/portfolio/"
	weight = 2

	[[menu.main]]
	name = "Blog"
	url = "/blog/"
	weight = 3
